# Allow kustomize to add frontend namespace to below kinds only
apiVersion: builtin
kind: NamespaceTransformer
metadata:
   name: not-important-to-example
   namespace: frontend
fieldSpecs:
  - path: metadata/namespace
    kind: Service
    create: true
  - path: metadata/namespace
    kind: Deployment
    create: true
  - path: metadata/namespace
    kind: NetworkPolicy
    create: true
  - path: metadata/namespace
    kind: ServiceAccount
    create: true
  - path: metadata/namespace
    kind: VirtualService
    create: true
  - path: metadata/namespace
    kind: Gateway
    create: true
  - path: metadata/namespace
    kind: AuthorizationPolicy
    create: true