artifacts:
  objects:
    location: gs://$_CACHE_BUCKET_NAME/artifacts
    paths:
      - '/workspace/frontend_hydrated.yaml'
steps:
- name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/skaffold-builder
  id: "setup"
  entrypoint: "/bin/bash"
  args:
    - '-xe'
    - -c
    - |
      cicd_sa_email=${_CICD_BUILD_SA}
      if [[ -n ${cicd_sa_email} ]]; then
        echo "Setting up gcloud for impersonation"
        gcloud config set auth/impersonate_service_account $cicd_sa_email
      fi
      skaffold config set default-repo $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY    
- name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/skaffold-builder
  id: "build-image"
  entrypoint: "/bin/bash"
  args:
    - '-xe'
    - -c
    - |
      cd 54-gke-app-cicd
      skaffold build --tag=$SHORT_SHA
      cd k8s/dev
      kustomize edit set image app="$_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/frontend:$SHORT_SHA"
      kustomize build . -o /workspace/frontend_hydrated.yaml
- name: "gcr.io/cloud-builders/gke-deploy"
  id: "deploy"
  args:
  - apply
  - --filename=/workspace/frontend_hydrated.yaml
  - --location=$_DEFAULT_REGION-a
  - --cluster=budita-d-$_DEFAULT_REGION
  - --project=prj-gke-d-clusters-3c96