apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  - image: frontend
    context: src/frontend
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
        - k8s/dev
  - name: prod
    deploy:
      kustomize:
        paths:
        - k8s/prod