patchesStrategicMerge:
- patch_deployment.yaml
# Pod ksa: frontend-dev
# gcp gsa: sa-frontend@prj-gke-d-clusters-3c96.iam.gserviceaccount.com
# They must match with 13-gke-workload-identity to use workload identity
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: frontend-dev
    - op: replace
      path: "/metadata/annotations/iam.gke.io~1gcp-service-account"
      value: sa-frontend@prj-gke-d-clusters-3c96.iam.gserviceaccount.com
  target:
    kind: ServiceAccount
    name: frontend
commonLabels:
  app: budita
  environment: dev
  service: frontend
namespace: frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../12-gke-platform-admins/budita-app/kustomize-bases/frontend
