artifacts:
  objects:
    location: gs://$_CACHE_BUCKET_NAME/artifacts
    paths:
      - '/artifacts/build-artifacts.json'

steps:

- name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/skaffold-builder
  id: "setup"
  entrypoint: "/bin/bash"
  args:
    - '-xe'
    - -c
    - |
      cicd_sa_email=${_CICD_BUILD_SA}
      if [[ -n ${cicd_sa_email} ]]; then
        echo "Setting up gcloud for impersonation"
        gcloud config set auth/impersonate_service_account $cicd_sa_email
      fi
      
- name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/skaffold-builder
  id: "build-image"
  entrypoint: "/bin/bash"
  args:
    - '-xe'
    - -c
    - |
      cd 54-gke-app
      skaffold build --default-repo=$_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY --tag=$SHORT_SHA --file-output=/artifacts/build-artifacts.json
      cd ..
      cd 54-gke-app/k8s/dev
      kustomize edit set image app="$_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY:$SHORT_SHA"
      kustomize build . -o /artifacts/hydrated_dev.yaml
  volumes:
  - path: '/artifacts'
    name: 'artifacts'
    
- name: gcr.io/cloud-builders/gke-deploy
  id: "deploy"
  entrypoint: "/bin/bash"
  args:
  - apply
  - --filename=/artifacts/hydrated_dev.yaml
  - --location=$_DEFAULT_REGION
  - --cluster=budita-d-$_DEFAULT_REGION
  - --project=prj-gke-d-clusters-3c96
  volumes:
  - path: '/artifacts'
    name: 'artifacts'