patchesStrategicMerge:
- patch_deployment.yaml
# ksa (frontend-dev) and gsa (sa-frontend@prj-gke-d-clusters-3c96.iam.gserviceaccount.com) must match with what's in 53-gke-workload-identity to leverage workload identity
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: frontend-dev
    - op: replace
      path: "/metadata/annotations/iam.gke.io~1gcp-service-account"
      value: sa-frontend@prj-gke-d-clusters-3c96.iam.gserviceaccount.com
  target:
    kind: ServiceAccount
    name: frontend
commonLabels:
  app: budita
  environment: dev
  service: frontend
namespace: frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../52-gke-platform-admins/budita-app/kustomize-bases/frontend
