patchesStrategicMerge:
- patch_deployment.yaml
commonLabels:
  app: budita
  environment: dev
  role: frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../52-gke-kustomize-bases
images:
- name: frontend
  newName: us-central1-docker.pkg.dev/prj-gke-c-cicd-pipeline-7989/prj-gke-c-cicd-pipeline-7989-cicd-image-repo/frontend
  newTag: abda88c
