patchesStrategicMerge:
- patch_deployment.yaml
commonLabels:
  app: budita
  environment: dev
  role: frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../52-gke-kustomize-bases
