kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: frontend-dev # Updated
      containers:
      - name: frontend
        image: frontend
        env:
        - name: PORT
          value: "8080"
        - name: TARGET
          value: world!!
        - name: ENVIRONMENT
          value: dev
      