kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      name: app
    spec:
      serviceAccountName: ksa
      containers:
      - name: app
        env:
        - name: PORT
          value: "8080"
        - name: TARGET
          value: world!!
        - name: ENVIRONMENT
          value: dev
      